# Generated by Django 5.0.2 on 2025-03-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_coach_reservationcoach_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationcoach',
            name='coach',
        ),
    ]
