# Generated by Django 5.0.2 on 2025-03-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_reservationcoach_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationcoach',
            name='total_price',
        ),
    ]
