# Generated by Django 5.0.2 on 2025-03-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservationcoach_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcoach',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.coach'),
        ),
        migrations.AddField(
            model_name='reservationcoach',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
